cc_library(
  name = "execution",
  hdrs = [
    "op.h",
    "op_iterator.h",
    "seq_scan.h",
  ],
  srcs = [
    "op.cc",
    "seq_scan.cc",
  ],
  deps = [
    "@com_google_absl//absl/status",
  ],
  visibility = ["//visibility:public"],
)
