cc_library(
  name = "storage",
  srcs = [
    "tuple_desc.cc",
  ],
  hdrs = [
    "tuple_desc.h",
    "td_item.h",
  ],
  deps = [
    "//komfydb/common:common",
    "@com_google_absl//absl/status",
  ],
)
