cc_library(
  name = "table_stats",
  srcs = ["table_stats.cc",],
  hdrs = ["table_stats.h",],
  deps = [
    "//komfydb/execution:op",
    "//komfydb/common:fields",
    "@com_google_absl//absl/status:statusor"
  ],
  visibility = ["//visibility:public"],
)
