cc_library(
  name = "common",
  hdrs = [
    "catalog.h",
    "database.h",
    "debug.h",
    "permissions.h",
    "type.h",
    "utility.h",
  ],
  srcs = [
    "catalog.cc",
    "database.cc",
    "debug.cc",
    "permissions.cc",
    "type.cc",
    "utility.cc",
  ],
  visibility = ["//visibility:public"],
)
